@ECHO OFF
C:
SET PATH=C:\BIN;C:\BLD
SET PATH_SEPARATOR=:
SET TMPDIR=C:\TMP
SET TEMP=C:\TMP
SET GO32TMP=C:\TMP
SET BLR=C:\BLD\BALROGG.EXE
SET BLR_TEST_DATA=C:\SRC\DATA
SET BLR_TEST_REGRESS=C:\SRC\REGRESS
SET BLR_TEST_LEVEL=@LEVEL@
CD C:\TMP
C:\BLD\TSUITE.EXE --report=C:\RESULT.LOG
IF ERRORLEVEL 1 GOTO FAILED
ECHO 0>C:\STATUS.TXT
GOTO FINISH
:FAILED
ECHO 1>C:\STATUS.TXT
:FINISH
C:\BIN\SYNC.EXE
C:\BIN\EXIT.EXE
